server:
  port: @data-server-port@
spring:
  application:
    name: data-module
  profiles:
    active: @package.environment@
  devtools:
    livereload:
      port: @data-devtools-livereload-port@

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapping/*.xml