spring:
  datasource:
    druid:
      url: "jdbc:mysql://127.0.0.1:3306/test?useSSL=false&characterEncoding=UTF-8&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      username: "root"
      password: "123456"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      initial-size: 10
      max-active: 50
      min-idle: 2
  redis:
    cluster:
      nodes: 1.redis:6381,2.redis:6381,4.redis:6381,4.redis:6381,5.redis:6381,6.redis:6381

dubbo:
  scan:
    base-packages: ${package}.data
  application:
    qos-port: @data-dubbo-qos-port@
  protocol:
    name: dubbo
    port: @data-dubbo-protocol-port@
  registry:
    address: zookeeper://1.zookeeper:2181?backup=2.zookeeper:2181,3.zookeeper:2181

application:
  dubbo:
    service-remote:
      passport:
        message-service-url: