spring:
  redis:
    cluster:
      nodes: 1.redis:6381,2.redis:6381,4.redis:6381,4.redis:6381,5.redis:6381,6.redis:6381

dubbo:
  scan:
    base-packages: com.sureland.api.controller
  application:
    qos-port: @api-dubbo-qos-port@
  protocol:
    name: dubbo
    port: @api-dubbo-protocol-port@
  registry:
    address: zookeeper://1.zookeeper:2181?backup=2.zookeeper:2181,3.zookeeper:2181

application:
  dubbo:
    service-remote:
      passport:
        message-service-url: